### PR TITLE
Fixes CompoundMultiIndex::FromObject not generating correct value combinations.

### LINKED ISSUE #106: Bug in walkVals function expanding the possible values in a compoundMultiIndex
When inserting an entry into a table with a compound multi index with a few multi indexers the walkVals function tries to expand all the possible values for a given entry which has multiple string slices. There is a bug in the recursive algoritm. In the example there is 36 possible values for the criterias index with 12 each of the last values of 301, 302 and 303 but this is not the case when the values are expanded.
```
package main

import (
"fmt"
"github.com/hashicorp/go-memdb"
)

func main() {
// Create a sample struct
type LineItem struct {
Id int
CreativeType string
DeviceType []string
InventoryType []string
Partners []string
Dayparts []string
}

// Create the DB schema
schema := &memdb.DBSchema{
	Tables: map[string]*memdb.TableSchema{
		"lineItem": &memdb.TableSchema{
			Name: "lineItem",
			Indexes: map[string]*memdb.IndexSchema{
				"id": &memdb.IndexSchema{
					Name:    "id",
					Unique:  true,
					Indexer: &memdb.IntFieldIndex{Field: "Id"},
				},
				"criterias": &memdb.IndexSchema{
					Name:   "criterias",
					Unique: false,
					Indexer: &memdb.CompoundMultiIndex{
						Indexes: []memdb.Indexer{
							&memdb.StringFieldIndex{Field: "CreativeType"},
							&memdb.StringSliceFieldIndex{Field: "DeviceType"},
							&memdb.StringSliceFieldIndex{Field: "InventoryType"},
							&memdb.StringSliceFieldIndex{Field: "Partners"},
							&memdb.StringSliceFieldIndex{Field: "Dayparts"},
						},
					},
				},
			},
		},
	},
}

err := schema.Validate()
if err != nil {
	panic(err)
}

// Create a new data base
db, err := memdb.NewMemDB(schema)
if err != nil {
	panic(err)
}

// Create a write transaction
txn := db.Txn(true)

// Insert some people
li := []*LineItem{
	{
		Id:            1045,
		CreativeType:  "video",
		DeviceType:    []string{"tv", "desktop", "mobile"},
		InventoryType: []string{"web", "app"},
		Partners:      []string{"microsoft", "google"},
		Dayparts:      []string{"301", "302", "303"},
	},
}
for _, p := range li {
	fmt.Printf("%+v\n", p)
	if err := txn.Insert("lineItem", p); err != nil {
		panic(err)
	}
}

// Commit the transaction
txn.Commit()

// Create read-only transaction
txn = db.Txn(false)
defer txn.Abort()

// Lookup by email
raw, err := txn.First("lineItem", "id", 1045)
if err != nil {
	panic(err)
}

// Say hi!
fmt.Printf("Hello %d!\n", raw.(*LineItem).Id)

// List by criterias index
it, err := txn.Get("lineItem", "criterias", "video", "tv", "app", "microsoft", "303")
if err != nil {
	panic(err)
}

fmt.Print("Found:")
for obj := it.Next(); obj != nil; obj = it.Next() {
	p := obj.(*LineItem)
	fmt.Printf("  %v\n", p)
}

// What? Can't find it?
it, err = txn.Get("lineItem", "criterias", "video", "tv", "app", "microsoft", "301")
if err != nil {
	panic(err)
}

fmt.Print("Found:")
for obj := it.Next(); obj != nil; obj = it.Next() {
	p := obj.(*LineItem)
	fmt.Printf("  %v\n", p)
}

}
```

### PR DESCRIPTION
**Pull request by WingGithub**
This is the fix suggested in #72 and also fixes #106 which refers to the same issue.

### CODE REVIEW

**Comment by WingGithub** [comment]
There seems to be an issue with the checks. I have signed the CLA but it does not show it.

**Comment by WingGithub** [comment]
Did you mean #72 has a clearer description? You're free to use the example in #106 since it my collaborators but the solution and initial discovery was in #72 and credit goes to @jp-mediakeys

**Comment by eculver** [comment]
I just saw the example in #106 and thought it would make a good test case. Regardless, I think we should add a test case for this fix if it isn't too crazy.

**Comment by WingGithub** [comment]
You are free to use the code in #106 for a test case but if you want me to write the test case, you'll have to be more explicit as some software engineers find it hard to read between the lines :>. If I am being requested to write the test case, it would be a stretch as I am not familiar with the projects test workflow and would need to go figure it all out first. Strange as it might seem, my career path has not required me to write any formal automated test cases but I can figure it out if required. Is it required?

**Pull request closed without merging**
