### PR TITLE
Simplify Watch using reflection

### PR DESCRIPTION
**Pull request by rlenglet**
Code is simplified and more efficient (cf. watch_test.go benchmark results).

### CODE REVIEW

**Comment by slackpad** [comment]
Hi @rlenglet thanks for the PR! I love the simplicity of this but I'm seeing it benchmark about 2.5X slower than what's in master. What kind of numbers are you seeing?

```
james@workpad go-memdb(master) $ go test -bench BenchmarkWatch
BenchmarkWatch-4           10000            113317 ns/op
PASS
ok      github.com/hashicorp/go-memdb   2.680s

james@workpad go-memdb(pr/36) $ go test -bench BenchmarkWatch
BenchmarkWatch-4            5000            296325 ns/op
PASS
ok      github.com/hashicorp/go-memdb   3.020s
```

**Comment by rlenglet** [comment]
Ah you're right, the performance is worse.

```
$ git branch
* master
  watch-reflect

$ go test -bench=BenchmarkWatch -benchtime=30s
BenchmarkWatch-4   	  500000	     90826 ns/op
PASS
ok  	github.com/hashicorp/go-memdb	47.850s

$ git branch
  master
* watch-reflect

$ go test -bench=BenchmarkWatch -benchtime=30s
BenchmarkWatch-4   	  200000	    200384 ns/op
PASS
ok  	github.com/hashicorp/go-memdb	43.933s
```

**Comment by slackpad** [comment]
Ok - this is in a pretty critical path for Consul and Nomad so I don't think we'd want to take the hit, even though your code is much nicer. We tried to make the ugly parts auto-generated, but they are still pretty ugly :-(

**Comment by rlenglet** [comment]
Unfortunately, there's not much to improve in the reflective version: 60% of CPU is spent in reflect.Select.

**Comment by slackpad** [comment]
Closing this out for now, doesn't seem like there's a good way forward with reflect. Appreciate the attempt though!

**Pull request closed without merging**
